"""added field for students 'room'

Revision ID: ba6226ec8663
Revises: 2ecc36c40f60
Create Date: 2025-11-06 10:42:20.356453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba6226ec8663"
down_revision: Union[str, Sequence[str], None] = "2ecc36c40f60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("room", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "room")
    # ### end Alembic commands ###
