"""nullable true for rfid in Student table

Revision ID: 7a0c4bf518f6
Revises: ba6226ec8663
Create Date: 2025-11-06 10:50:44.877087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a0c4bf518f6"
down_revision: Union[str, Sequence[str], None] = "ba6226ec8663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "rfid", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "rfid", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
